name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build application
        run: make build asset-catalog

      - name: Create app zip
        run: |
          zip -r HFJobs.zip HFJobs.app
          echo "APP_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: HFJobs.zip
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Upload artifact for non-tag builds
        uses: actions/upload-artifact@v4
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          name: HFJobs-App
          path: HFJobs.zip
          retention-days: 7